Fixes unknowns alert
SatcherInstitute/health-equity-tracker pull request #1374
Opened 2021-12-28 19:35 UTC by benhammondmusic

"0% of COVID-19 vaccinations reported unknown age. The map below displays data for cases where age was unknown." was showing up even when there wasn't unknown data available and there for no map. 

![Screen Shot 2021-12-28 at 12 31 50 PM](https://user-images.githubusercontent.com/41567007/147600799-7ba544fc-e404-4fc4-8e26-5e3a07ac8e56.png)

2021-12-28 22:03 UTC, joshzarrabi commented
@benhammondmusic Now im seeing no alert at all under race/ethnicity
<img width="1010" alt="Screen Shot 2021-12-28 at 2 02 36 PM" src="https://user-images.githubusercontent.com/3689026/147610395-0dcfeeb8-cbfd-4083-bc34-2bc292acf300.png">

2021-12-28 22:04 UTC, joshzarrabi requested changes
Alert is not showing up under race/ethnicity

2021-12-29 16:34 UTC, benhammondmusic commented
## Show Unknown Percent Alert without MAP text and with CHART text; show MISSING DATA for map
![Screen Shot 2021-12-29 at 9 32 28 AM](https://user-images.githubusercontent.com/41567007/147683855-4852bffe-6687-4be6-a4cd-8e355a667b43.png)

## Show Unknown Percent Alert with MAP/CHART text
![Screen Shot 2021-12-29 at 9 22 38 AM](https://user-images.githubusercontent.com/41567007/147683042-3cbdbaac-011b-43a2-ac11-06d1144e7cc6.png)

## Show Missing Data Alert (no race breakdowns for the state)
![Screen Shot 2021-12-29 at 9 16 41 AM](https://user-images.githubusercontent.com/41567007/147683033-f93d14cb-96fe-4c4d-ac0d-14d9dcbed191.png)

## Show Alert (no data, state is partly suppressed for COVID)
![Screen Shot 2021-12-29 at 9 19 50 AM](https://user-images.githubusercontent.com/41567007/147683038-83f78d96-7016-4c79-a8c5-f4366cfa249a.png)

## Don't Show Missing Data or 0% Alert (survey data is complete and by design has no unknowns)
![Screen Shot 2021-12-29 at 9 21 33 AM](https://user-images.githubusercontent.com/41567007/147683039-7f2acadc-4c54-4bfb-91fb-5cdc3a8c3f6e.png)

2021-12-30 00:56 UTC, joshzarrabi approved these changes

2021-12-30 04:56 UTC, merged