Svi frontend
SatcherInstitute/health-equity-tracker pull request #1630
Opened 2022-06-15 21:17 UTC by eriwarr

## Preview Link

<a href="https://deploy-preview-1234--health-equity-tracker.netlify.app/" target="_blank">
  <img width="150"  src="https://healthequitytracker.org/img/appbar/AppbarLogo.png" alt="" /><br />
Click to demo updates </a>   <-- Update this link once you have PR# 

## Description

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Refactor (code improvement that doesn't affect UI)
- Chore (developer productivity fix that doesn't affect the user)

2022-06-30 22:06 UTC, benhammondmusic commented
Looking great! I was just testing it on mobile and I think we need to ensure the "full profile" button goes below the new alert. This isn't an issue on desktop because they're side by side but we should try and vertically swap them for mobile 

 ![image](https://user-images.githubusercontent.com/41567007/176786796-b401d588-b415-4c04-8057-757cc0b6184d.jpeg)

2022-07-11 19:50 UTC, benhammondmusic commented on frontend/src/cards/ui/SviAlert.tsx
> +    return "#d32f2f";
If possible I'd love to stay consistent with our styling. Specifically:
- make a scss module for this new SviAlert component
- import scss variables
- only use sass variables like `sass.altGreen`; add new entries to the variable files if we don't have an existing color that works

2022-07-11 19:51 UTC, benhammondmusic commented on frontend/src/cards/ui/SviAlert.tsx
> +            <span style={{ color: color, fontWeight: "bold" }}>
I know there are haters out there, but we generally just use `<b>` tags for bold text. Perhaps down the line we should create a global class to handle emphasized text, but for now let's just stay consistent with `<b>`. In general I think we should avoid inline CSS as well, except rare places where it's needed

2022-07-11 19:53 UTC, benhammondmusic commented on frontend/src/cards/PopulationCard.tsx
> +      Breakdowns.forFips(props.fips).andAge(onlyInclude("All"))
Can you file a new issue to switch this logic from using `Age` when we should really just use a new breakdown type for data that applies to the entire geography ?

2022-07-13 19:23 UTC, benhammondmusic requested changes

2022-07-13 19:23 UTC, benhammondmusic commented on frontend/src/cards/Card.module.scss
> +}
I think the Profile button should be left aligned when it's bumped to a new line on narrow screens, right? 
<img width="890" alt="Screen Shot 2022-07-13 at 12 40 59 PM" src="https://user-images.githubusercontent.com/41567007/178814215-25544098-698d-4469-8dc5-1fe3bb4e7219.png">

2022-07-13 19:23 UTC, benhammondmusic commented on frontend/src/cards/Card.module.scss
> +}
Like this instead? I think it looks better on the left but open to other ideas
<img width="728" alt="Screen Shot 2022-07-13 at 1 21 10 PM" src="https://user-images.githubusercontent.com/41567007/178814667-914a84fd-d357-4b3f-b4c0-e13c0341e0c6.png">

2022-07-13 22:41 UTC, joshzarrabi commented
@eriwarr @benhammondmusic , For now I think its confusing that clicking the SVI takes you to the top of the methodology page. I know we want to redesign that whole flow but as it stands right now I don't think it works super well. How hard would it be to add an anchor to the SVI section of the methodology page?

2022-07-15 19:56 UTC, benhammondmusic approved these changes
Awesome!! Thanks so much man; I appreciate the attention to detail and the extra effort to continuously streamline and standardize the code base

2022-07-15 20:25 UTC, merged