Svi backend
SatcherInstitute/health-equity-tracker pull request #1651
Opened 2022-07-06 17:33 UTC by eriwarr

## Preview Link

<a href="https://deploy-preview-1234--health-equity-tracker.netlify.app/" target="_blank">
  <img width="150"  src="https://healthequitytracker.org/img/appbar/AppbarLogo.png" alt="" /><br />
Click to demo updates </a>   <-- Update this link once you have PR# 

## Description

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Refactor (code improvement that doesn't affect UI)
- Chore (developer productivity fix that doesn't affect the user)

2022-07-11 20:59 UTC, joshzarrabi requested changes

2022-07-11 20:59 UTC, joshzarrabi commented on python/datasources/cdc_svi_county.py
> +BASE_CDC_URL = 'https://data.cdc.gov/resource/8xkx-amqh.csv'
@eriwarr I think we can delete these two lines

2022-07-11 20:59 UTC, joshzarrabi commented on python/tests/datasources/test_cdc_svi_county.py
> +# @mock.patch('ingestion.gcs_to_bq_util.load_csv_as_df_from_data_dir', return_value=get_real_svi_as_df())
Lets remove this commented out test

2022-07-11 20:59 UTC, joshzarrabi commented on python/tests/datasources/test_cdc_svi_county.py
> +    # assert format_svi(2) == ValueError
Do we want this line?

2022-07-11 21:25 UTC, joshzarrabi approved these changes
Looks great, thank you! Can you add some more context into the pr comments and link to the SVI issue please?

2022-07-12 00:14 UTC, benhammondmusic approved these changes
awesome!

2022-07-12 14:33 UTC, merged