Inequitable share frontend
SatcherInstitute/health-equity-tracker pull request #1838
Opened 2022-10-07 21:12 UTC by joshzarrabi

## Preview Link

<a href="https://deploy-preview-1234--health-equity-tracker.netlify.app/exploredata?onboard=false" target="_blank">
  <img width="150"  src="https://healthequitytracker.org/img/appbar/AppbarLogo.png" alt="" /><br />
Click to demo updates </a> 

## Description

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality or content)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Refactor (code improvement that doesn't affect UI)
- Chore (developer productivity fix that doesn't affect the user)

2022-10-12 03:53 UTC, benhammondmusic commented
<img width="1787" alt="Screen Shot 2022-10-11 at 9 50 05 PM" src="https://user-images.githubusercontent.com/41567007/195246075-d47dcab6-91d7-4dff-95ea-036694bdcb9e.png">

2022-10-24 18:46 UTC, eriwarr requested changes
This is the only thing I noticed. Everything else looks great!!

![Unknown Map](https://user-images.githubusercontent.com/72993442/197601941-594d8b42-0bc7-489c-ac9a-e95b3214a582.jpg)

2022-10-24 18:46 UTC, eriwarr commented on frontend/src/data/config/MetricConfig.ts
> -          chartTitle: "Share of total COVID-19 cases with unknown",
Removing the _chartTitle_  prop will cause the chart title on the Unknown maps to be partially blank.

2022-10-24 19:20 UTC, joshzarrabi commented
Looks good to me! Just update the col name to https://github.com/SatcherInstitute/health-equity-tracker/pull/1857 and we should be good to go.

2022-10-24 20:11 UTC, eriwarr approved these changes
Great job Ben!!!

2022-10-24 20:18 UTC, merged