Pct share sanity check
SatcherInstitute/health-equity-tracker pull request #1943
Opened 2022-12-20 17:32 UTC by eriwarr

## Preview Link

<a href="https://deploy-preview-1234--health-equity-tracker.netlify.app/exploredata" target="_blank">
  <img width="150"  src="https://healthequitytracker.org/img/appbar/AppbarLogo.png" alt="" /><br />
Click to demo updates </a> 

## Description

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality or updates content)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Refactor (code improvement that doesn't affect UI)
- Chore (developer productivity fix that doesn't affect the user)

2023-01-06 19:47 UTC, joshzarrabi requested changes

2023-01-06 19:47 UTC, joshzarrabi commented on python/tests/sanity_checks/test_sanity_check.py
> +    return result
I think these should be `assert`s. You can do it all in one line: like `assert check_pct_values(df)`

2023-01-06 19:47 UTC, joshzarrabi commented on python/tests/sanity_checks/test_sanity_check.py
> +
I think in this file you should also test an error case. Like a case where you expect it to fail and error. See https://github.com/SatcherInstitute/health-equity-tracker/blob/89f6457cf5f1a4dcef520cfd349ce73a0de61025/python/tests/ingestion/test_dataset_utils.py#L278-L281 as an example of how to do that.

2023-01-06 19:47 UTC, joshzarrabi commented on python/tests/sanity_checks/test_sanity_check.py
> +    df = pd.read_json(CDC_RESTRICTED['sex_county_time'], dtype=test_dtype)
Nice job testing time

2023-01-06 19:47 UTC, joshzarrabi commented on python/sanity_checks/build/lib/sanity_checks/sanity_check.py
> +import pandas as pd
I dont think this file should be checked in at all.

2023-01-06 19:47 UTC, joshzarrabi commented on python/sanity_checks/sanity_check.py
> +def generate_cols(df: pd.DataFrame):
Do we use this file? It looks like you copied the code to the `airflow/dags/sanity_check.py` file and use that in the pipeline. We should use the code that we run our tests on.

2023-01-09 19:29 UTC, benhammondmusic approved these changes
looks good to me; i've started doing screenshots of bigquery / airflow / backend stuff for my backend PRs as I think it can be helpful when reviewing and referencing exactly what these backend changes are doing. Maybe consider taking a few screenshots of the printout from a successful run and a run where things aren't adding up properly

2023-01-09 20:18 UTC, joshzarrabi approved these changes
Thank you Eric!

2023-01-09 20:18 UTC, joshzarrabi commented on airflow/dags/util.py
> +        table_name = "{}.{}.{}".format(
Would you mind switching this to an `fstring`

2023-01-09 20:18 UTC, joshzarrabi commented on airflow/dags/test_sanity_check.py
> +import os
This looks good but I think you should put it in a `test` directory

2023-01-09 22:50 UTC, eriwarr commented
> looks good to me; i've started doing screenshots of bigquery / airflow / backend stuff for my backend PRs as I think it can be helpful when reviewing and referencing exactly what these backend changes are doing. Maybe consider taking a few screenshots of the printout from a successful run and a run where things aren't adding up properly
> looks good to me; i've started doing screenshots of bigquery / airflow / backend stuff for my backend PRs as I think it can be helpful when reviewing and referencing exactly what these backend changes are doing. Maybe consider taking a few screenshots of the printout from a successful run and a run where things aren't adding up properly

Great point! I'll update the PR to include them.

2023-01-09 22:51 UTC, merged