FRONTEND: Adds HIV Diagnoses
SatcherInstitute/health-equity-tracker pull request #1973
Opened 2023-01-24 15:08 UTC by benhammondmusic

## Description

## Preview Link

<a href="https://deploy-preview-234--health-equity-tracker.netlify.app/exploredata" target="_blank">
  <img width="150"  src="https://healthequitytracker.org/img/appbar/AppbarLogo.png" alt="" /><br />
Click to demo updates </a> 

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality or updates content)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Refactor (code improvement that doesn't affect UI)
- Chore (developer productivity fix that doesn't affect the user)

2023-02-13 15:33 UTC, eriwarr approved these changes
Looks great. Awesome job, @benhammondmusic!

2023-02-13 20:01 UTC, joshzarrabi requested changes

2023-02-13 20:01 UTC, joshzarrabi commented on frontend/src/data/variables/HivProvider.ts
> +      population_pct: "hiv_population_pct",
Lets do this on the backend.

2023-02-13 20:01 UTC, joshzarrabi commented
Looks great, lets move the renaming to the backend first

2023-02-14 15:38 UTC, joshzarrabi approved these changes

2023-02-14 15:38 UTC, merged