Adds nightly e2e for covid cases, deaths, and hospitalizations
SatcherInstitute/health-equity-tracker pull request #2738
Opened 2024-01-16 23:43 UTC by JDemlow

# Description and Motivation
Closes #2558
Closes #2557
Closes #2556

## Has this been tested? How?

Tests pass locally

<img width="940" alt="covid-cases-deaths-hospitalizations" src="https://github.com/SatcherInstitute/health-equity-tracker/assets/14945785/62ed9dfc-81be-4404-b9a4-4a0e1fabaeec">

## Types of changes

(leave all that apply)

- New content or feature

## New frontend preview link is below in the Netlify comment 😎

2024-01-16 23:50 UTC, benhammondmusic requested changes

2024-01-16 23:50 UTC, benhammondmusic commented on frontend/playwright-tests/covid_cases_deaths_hospitalizations.nightly.spec.ts
> +    'http://localhost:3000/exploredata?mls=1.covid-3.00&group1=All'
We have to make sure that the base url isn't hard coded in; just use relative urls instead throughout

2024-01-16 23:50 UTC, benhammondmusic commented on frontend/playwright-tests/covid_cases_deaths_hospitalizations.nightly.spec.ts
> +test('Covid Cases, Deaths, Hospitalizations', async ({ page }) => {
Let's actually split it into 3 test() functions inside this one single file. Then it'll be easier to identify a test failure in a particular datatype. Just have each new test start right before where you're having it go to local host (and make those relative urls)

2024-01-17 00:02 UTC, JDemlow reviewed
The latest commit splits the test into three test blocks and fixes the relative URL issue

2024-01-17 00:17 UTC, JDemlow commented
Ok! The following has been fixed:

- Test is split into three test blocks
- Fixed relative URL problem
- All refactored code has been reinserted
- Screenshot updated
- All checks pass

I believe we're good now 👍

2024-01-17 00:22 UTC, benhammondmusic approved these changes
Nice!!!

2024-01-17 00:27 UTC, merged