Setting up mc mh
SatcherInstitute/health-equity-tracker pull request #3534
Opened 2024-08-05 19:42 UTC by JDemlow

# Description and Motivation

## Has this been tested? How?

## Screenshots (if appropriate)

## Types of changes

(leave all that apply)

- Bug fix
- New content or feature
- Refactor / chore

## New frontend preview link is below in the Netlify comment 😎

2024-08-21 20:58 UTC, benhammondmusic requested changes

2024-08-21 20:58 UTC, benhammondmusic commented on frontend/src/data/providers/GunViolenceYouthProvider.ts
Do you mind removing these gun violence files from this PR? I think it's mostly linting stuff but definitely best practice to roll these changes back and keep the PR totally Focused on maternal mortality frontend stuff. 

A quick way to roll back is locally checkout the file from origin/main like `git checkout origin/main -- some/weird/unrelated/file.tsx`

2024-08-21 21:29 UTC, JDemlow commented on frontend/src/data/providers/GunViolenceYouthProvider.ts
Sorry, did you want all of the Gun Violence files removed from the provider folder, or just the specified GunViolenceYouthProvider.ts?

2024-08-21 21:49 UTC, JDemlow commented
Only files showing as changed are related to MM. Should be good now!

2024-08-22 17:57 UTC, benhammondmusic approved these changes
great! just remove those console logs/warns and then merge it in! thanks :)

2024-08-22 17:57 UTC, benhammondmusic commented on frontend/src/data/providers/MaternalMortalityProvider.ts
> +    console.log('Loading dataset with ID:', specificDatasetId) // Debugging log
let's make sure we remove all these logs

2024-08-22 17:57 UTC, benhammondmusic commented on frontend/src/data/providers/MaternalMortalityProvider.ts
> +    console.log('After filtering by geo:', df.toArray()) // Check data after filtering by geography
remove

2024-08-22 17:57 UTC, benhammondmusic commented on frontend/src/data/providers/MaternalMortalityProvider.ts
> +      console.warn('No data after filtering, returning empty response')
remove

2024-08-22 17:57 UTC, benhammondmusic commented on frontend/src/data/providers/MaternalMortalityProvider.ts
> +    console.log('After applying demographic breakdown filters:', df.toArray()) // Check data after applying demographic filters
remove

2024-08-22 17:57 UTC, benhammondmusic commented on frontend/src/data/providers/MaternalMortalityProvider.ts
> +    console.log('Final data returned:', df.toArray()) // Final check before returning data
remove

2024-08-28 17:27 UTC, merged