Age Accumulation Buckets
SatcherInstitute/health-equity-tracker pull request #632
Opened 2021-04-21 15:24 UTC by Sethvg

2021-04-22 23:33 UTC, vanshkumar commented
Looks like build is breaking, could you fix that?

2021-04-27 04:48 UTC, vanshkumar commented
Before we start combining buckets to make the custom buckets requested by MSM, it would be worthwhile to spend a bit of time figuring out why the age "16" doesn't show up in the data.. is there a bug in the parsing code somewhere? Does the data itself just not include it?

2021-04-27 20:56 UTC, joshzarrabi requested changes

2021-04-27 20:56 UTC, joshzarrabi commented on python/datasources/acs_poverty.py
> +    else:
Don't need this `else` I think

2021-04-27 20:56 UTC, joshzarrabi commented on python/datasources/acs_poverty.py
> +            assert above != -1
I don't really like the idea of having `assert` statements in our code. I would prefer checking the value and `raising` an error if it is wrong.

2021-04-27 21:31 UTC, joshzarrabi approved these changes

2021-04-27 22:21 UTC, merged