Make unknowns map for county-level territories work
SatcherInstitute/health-equity-tracker pull request #992
Opened 2021-06-16 22:24 UTC by vanshkumar

2021-06-16 23:11 UTC, joshzarrabi commented
Looks great, good to show the data that we have :)

2021-06-16 23:11 UTC, joshzarrabi approved these changes

2021-06-17 21:07 UTC, joshzarrabi requested changes
We decided to only show the unknowns map when we don't have population data, because showing the percentage of cases without the corresponding population data can be misleading and does not present the data in the proper context

2021-06-18 03:56 UTC, vanshkumar commented
> We decided to only show the unknowns map when we don't have population data, because showing the percentage of cases without the corresponding population data can be misleading and does not present the data in the proper context

Changed

2021-06-21 16:36 UTC, joshzarrabi approved these changes

2021-06-21 17:22 UTC, merged